apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: remedy
  labels:
    app: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: thisaru01/remedy-patient-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: remedy-env
                  key: PATIENT_MONGO_URI
          envFrom:
            - secretRef:
                name: remedy-env
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: remedy
spec:
  type: ClusterIP
  selector:
    app: patient-service
  ports:
    - name: http
      port: 5000
      targetPort: 5000
