apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  namespace: remedy
  labels:
    app: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: thisaru01/remedy-telemedicine-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: remedy-env
                  key: TELEMEDICINE_MONGO_URI
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:5000"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5000"
          envFrom:
            - secretRef:
                name: remedy-env
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
  namespace: remedy
spec:
  type: ClusterIP
  selector:
    app: telemedicine-service
  ports:
    - name: http
      port: 5000
      targetPort: 5000
