apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: remedy
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: thisaru01/remedy-notification-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5007
          env:
            - name: PORT
              value: "5007"
          envFrom:
            - secretRef:
                name: remedy-env
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: remedy
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 5007
      targetPort: 5007
