apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: remedy
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: thisaru01/remedy-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BASE_URL
              value: "http://localhost:30080/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: remedy
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      nodePort: 30173
